# Generated by Django 4.0.3 on 2022-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('phone_num', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=45)),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
            ],
        ),
    ]
