# Generated by Django 4.0.3 on 2022-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AlterField(
            model_name='products',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
